version: "3"

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80 # web ui

  minio1:
    image: minio/minio:RELEASE.2020-11-25T22-36-25Z
    volumes:
      - data1:/data1
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${FILE_STORAGE_ACCESS_KEY}
      MINIO_SECRET_KEY: ${FILE_STORAGE_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mailhog:
    image: mailhog/mailhog
    user: root
    environment:
      MAILHOG_USERNAME: ${MAIL_USERNAME}
      MAILHOG_PASSWORD: ${MAIL_PASSWORD}
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - mailhog:/maildir
    ports:
      - 1025:1025 # SMTP
      - 8025:8025 # web ui

volumes:
  postgres-data:
  pgadmin:
  data1:
  mailhog:
